### PR TITLE
Fixes #14 where attribute syntax not appending classes correctly

### LINKED ISSUE #14: Attribute syntax for appending classes doesn't work correctly
``` javascripts
var template = '<div class="dog" />';
var data = { 'dog@class': 'cat' }
var result = facile(template, data);

// result is:
//        <div class="cat"></div>
// but it should be:
//        <div class="dog cat"></div>
```

### PR DESCRIPTION
**Pull request by benjreinhart**
https://github.com/EndangeredMassa/facile.js/issues/14

### CODE REVIEW

**Comment by benjreinhart** [comment]
Umm, not seeing what the actual travis failure is, but I do see that it "Can't open 'run-jasmine.coffee'". Not sure what's going on, but all tests pass locally for me.

File: facile.coffee [hunk 1]
```diff
@@ -80,7 +71,10 @@ bindValue = ($template, key, value) ->
     if tagName($el) == 'SELECT'
       $el.find("option[value='#{value}']").attr('selected', 'selected')
     else
-      $el.attr(attr, value)
+      if attr == 'class'
+        $el.addClass(value)
+      else
+        $el.attr(attr, value)
```
Comment (EndangeredMassa) [inline facile.coffee]: This logic should be extracted into a setValue method so that we don't duplicate it here and below.

**Comment by EndangeredMassa** [comment]
Yeah, don't worry about travis-ci right now.

Nice catch! Thanks for the PR. I'm happy to accept it after the small change I mentioned above.
